In [57]:
import pandas as pd

In [58]:
import numpy as np

In [59]:
df = pd.read_csv("index_1.csv")

In [60]:
df.head(20)

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte
5,2024-03-01,2024-03-01 15:39:47.726,card,ANON-0000-0000-0005,33.8,Americano with Milk
6,2024-03-01,2024-03-01 16:19:02.756,card,ANON-0000-0000-0006,38.7,Hot Chocolate
7,2024-03-01,2024-03-01 18:39:03.580,card,ANON-0000-0000-0007,33.8,Americano with Milk
8,2024-03-01,2024-03-01 19:22:01.762,card,ANON-0000-0000-0008,38.7,Cocoa
9,2024-03-01,2024-03-01 19:23:15.887,card,ANON-0000-0000-0008,33.8,Americano with Milk
10,2024-03-01,2024-03-01 19:29:17.391,card,ANON-0000-0000-0009,33.8,Americano with Milk
11,2024-03-02,2024-03-02 10:22:06.957,card,ANON-0000-0000-0010,28.9,Americano
12,2024-03-02,2024-03-02 10:30:35.668,cash,NaN,40.0,Latte
13,2024-03-02,2024-03-02 10:41:41.249,card,ANON-0000-0000-0011,33.8,Americano with Milk
14,2024-03-02,2024-03-02 11:59:45.484,card,ANON-0000-0000-0012,33.8,Americano with Milk
15,2024-03-02,2024-03-02 14:38:35.535,card,ANON-0000-0000-0013,28.9,Americano
16,2024-03-02,2024-03-02 16:37:24.475,card,ANON-0000-0000-0014,33.8,Americano with Milk
17,2024-03-02,2024-03-02 17:34:54.969,card,ANON-0000-0000-0004,28.9,Americano
18,2024-03-03,2024-03-03 10:10:43.981,cash,NaN,40.0,Latte
19,2024-03-03,2024-03-03 10:27:18.561,card,ANON-0000-0000-0015,38.7,Latte

In [61]:
df.describe()

             money
count  3636.000000
mean     31.746859
std       4.919926
min      18.120000
25%      27.920000
50%      32.820000
75%      35.760000
max      40.000000

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   object
 1   datetime     3636 non-null   object
 2   cash_type    3636 non-null   object
 3   card         3547 non-null   object
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   object
dtypes: float64(1), object(5)
memory usage: 170.6+ KB

In [63]:
df.shape

(3636, 6)

In [64]:
df.isnull().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

In [65]:
df.duplicated().sum()

np.int64(0)

## Data Cleaning

In [66]:
clean_df = df.copy()

In [67]:
clean_df["card"] = clean_df["card"].fillna("Cash Payment")
clean_df["coffee_name"] = clean_df["coffee_name"].str.strip()

In [68]:
df.duplicated(subset=["card" , "datetime"])

0       False
1       False
2       False
3       False
4       False
        ...
3631    False
3632    False
3633    False
3634    False
3635    False
Length: 3636, dtype: bool

In [69]:
df.tail(20)

,date,datetime,cash_type,card,money,coffee_name
3616,2025-03-21,2025-03-21 18:52:12.666,card,ANON-0000-0000-0507,35.76,Latte
3617,2025-03-21,2025-03-21 18:59:24.271,card,ANON-0000-0000-1170,25.96,Americano
3618,2025-03-22,2025-03-22 09:05:13.059,card,ANON-0000-0000-1274,30.86,Americano with Milk
3619,2025-03-22,2025-03-22 10:30:09.403,card,ANON-0000-0000-1152,30.86,Americano with Milk
3620,2025-03-22,2025-03-22 11:14:05.960,card,ANON-0000-0000-1259,35.76,Hot Chocolate
3621,2025-03-22,2025-03-22 11:41:20.579,card,ANON-0000-0000-1279,35.76,Cocoa
3622,2025-03-22,2025-03-22 12:18:27.491,card,ANON-0000-0000-1313,30.86,Americano with Milk
3623,2025-03-22,2025-03-22 12:25:59.676,card,ANON-0000-0000-1306,25.96,Americano
3624,2025-03-22,2025-03-22 13:06:21.590,card,ANON-0000-0000-1309,25.96,Americano
3625,2025-03-22,2025-03-22 13:23:17.918,card,ANON-0000-0000-1267,30.86,Americano with Milk
3626,2025-03-22,2025-03-22 15:57:58.183,card,ANON-0000-0000-1302,21.06,Espresso
3627,2025-03-22,2025-03-22 16:26:59.766,card,ANON-0000-0000-1274,35.76,Latte
3628,2025-03-22,2025-03-22 17:53:35.942,card,ANON-0000-0000-1274,30.86,Americano with Milk
3629,2025-03-22,2025-03-22 19:16:52.727,card,ANON-0000-0000-1314,30.86,Americano with Milk
3630,2025-03-23,2025-03-23 10:07:11.278,card,ANON-0000-0000-1196,35.76,Latte
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [70]:
clean_df['datetime'] = pd.to_datetime(clean_df['datetime'])
clean_df['datetime'] = pd.to_datetime(clean_df['datetime'].dt.floor('s'))

In [71]:
clean_df.nlargest(7, 'money')

,date,datetime,cash_type,card,money,coffee_name
12,2024-03-02,2024-03-02 10:30:35,cash,Cash Payment,40.0,Latte
18,2024-03-03,2024-03-03 10:10:43,cash,Cash Payment,40.0,Latte
46,2024-03-07,2024-03-07 10:08:58,cash,Cash Payment,40.0,Latte
49,2024-03-07,2024-03-07 11:25:43,cash,Cash Payment,40.0,Latte
60,2024-03-09,2024-03-09 11:49:37,cash,Cash Payment,40.0,Hot Chocolate
76,2024-03-10,2024-03-10 10:06:02,cash,Cash Payment,40.0,Latte
81,2024-03-11,2024-03-11 10:18:46,cash,Cash Payment,40.0,Latte

In [72]:
clean_df['money'] = pd.to_numeric(clean_df['money'], errors = 'coerce')

In [73]:
print(df['coffee_name'].unique())

['Latte' 'Hot Chocolate' 'Americano' 'Americano with Milk' 'Cocoa'
 'Cortado' 'Espresso' 'Cappuccino']

In [74]:
clean_df['coffee_name'] = clean_df['coffee_name'].str.strip()

In [75]:
clean_df = clean_df.map(lambda x: x.strip() if isinstance(x, str) else x)

In [76]:
clean_df.head(20)

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14,card,ANON-0000-0000-0004,38.7,Latte
5,2024-03-01,2024-03-01 15:39:47,card,ANON-0000-0000-0005,33.8,Americano with Milk
6,2024-03-01,2024-03-01 16:19:02,card,ANON-0000-0000-0006,38.7,Hot Chocolate
7,2024-03-01,2024-03-01 18:39:03,card,ANON-0000-0000-0007,33.8,Americano with Milk
8,2024-03-01,2024-03-01 19:22:01,card,ANON-0000-0000-0008,38.7,Cocoa
9,2024-03-01,2024-03-01 19:23:15,card,ANON-0000-0000-0008,33.8,Americano with Milk
10,2024-03-01,2024-03-01 19:29:17,card,ANON-0000-0000-0009,33.8,Americano with Milk
11,2024-03-02,2024-03-02 10:22:06,card,ANON-0000-0000-0010,28.9,Americano
12,2024-03-02,2024-03-02 10:30:35,cash,Cash Payment,40.0,Latte
13,2024-03-02,2024-03-02 10:41:41,card,ANON-0000-0000-0011,33.8,Americano with Milk
14,2024-03-02,2024-03-02 11:59:45,card,ANON-0000-0000-0012,33.8,Americano with Milk
15,2024-03-02,2024-03-02 14:38:35,card,ANON-0000-0000-0013,28.9,Americano
16,2024-03-02,2024-03-02 16:37:24,card,ANON-0000-0000-0014,33.8,Americano with Milk
17,2024-03-02,2024-03-02 17:34:54,card,ANON-0000-0000-0004,28.9,Americano
18,2024-03-03,2024-03-03 10:10:43,cash,Cash Payment,40.0,Latte
19,2024-03-03,2024-03-03 10:27:18,card,ANON-0000-0000-0015,38.7,Latte

## Date Processing

In [77]:
clean_df['quantity'] = 1

In [78]:
clean_df.tail(8)

,date,datetime,cash_type,card,money,coffee_name,quantity
3628,2025-03-22,2025-03-22 17:53:35,card,ANON-0000-0000-1274,30.86,Americano with Milk,1
3629,2025-03-22,2025-03-22 19:16:52,card,ANON-0000-0000-1314,30.86,Americano with Milk,1
3630,2025-03-23,2025-03-23 10:07:11,card,ANON-0000-0000-1196,35.76,Latte,1
3631,2025-03-23,2025-03-23 10:34:54,card,ANON-0000-0000-1158,35.76,Cappuccino,1
3632,2025-03-23,2025-03-23 14:43:37,card,ANON-0000-0000-1315,35.76,Cocoa,1
3633,2025-03-23,2025-03-23 14:44:16,card,ANON-0000-0000-1315,35.76,Cocoa,1
3634,2025-03-23,2025-03-23 15:47:28,card,ANON-0000-0000-1316,25.96,Americano,1
3635,2025-03-23,2025-03-23 18:11:38,card,ANON-0000-0000-1275,35.76,Latte,1

In [79]:
clean_df.drop("date", axis = 1 , inplace = True)
clean_df.head()

,datetime,cash_type,card,money,coffee_name,quantity
0,2024-03-01 10:15:50,card,ANON-0000-0000-0001,38.7,Latte,1
1,2024-03-01 12:19:22,card,ANON-0000-0000-0002,38.7,Hot Chocolate,1
2,2024-03-01 12:20:18,card,ANON-0000-0000-0002,38.7,Hot Chocolate,1
3,2024-03-01 13:46:33,card,ANON-0000-0000-0003,28.9,Americano,1
4,2024-03-01 13:48:14,card,ANON-0000-0000-0004,38.7,Latte,1

In [80]:
clean_df.isnull().sum()

datetime       0
cash_type      0
card           0
money          0
coffee_name    0
quantity       0
dtype: int64

In [81]:
clean_df.to_csv('my_cleanedKaggle42_data.csv' , index=False)

In [82]:
clean_df.head(30)

,datetime,cash_type,card,money,coffee_name,quantity
0,2024-03-01 10:15:50,card,ANON-0000-0000-0001,38.7,Latte,1
1,2024-03-01 12:19:22,card,ANON-0000-0000-0002,38.7,Hot Chocolate,1
2,2024-03-01 12:20:18,card,ANON-0000-0000-0002,38.7,Hot Chocolate,1
3,2024-03-01 13:46:33,card,ANON-0000-0000-0003,28.9,Americano,1
4,2024-03-01 13:48:14,card,ANON-0000-0000-0004,38.7,Latte,1
5,2024-03-01 15:39:47,card,ANON-0000-0000-0005,33.8,Americano with Milk,1
6,2024-03-01 16:19:02,card,ANON-0000-0000-0006,38.7,Hot Chocolate,1
7,2024-03-01 18:39:03,card,ANON-0000-0000-0007,33.8,Americano with Milk,1
8,2024-03-01 19:22:01,card,ANON-0000-0000-0008,38.7,Cocoa,1
9,2024-03-01 19:23:15,card,ANON-0000-0000-0008,33.8,Americano with Milk,1
10,2024-03-01 19:29:17,card,ANON-0000-0000-0009,33.8,Americano with Milk,1
11,2024-03-02 10:22:06,card,ANON-0000-0000-0010,28.9,Americano,1
12,2024-03-02 10:30:35,cash,Cash Payment,40.0,Latte,1
13,2024-03-02 10:41:41,card,ANON-0000-0000-0011,33.8,Americano with Milk,1
14,2024-03-02 11:59:45,card,ANON-0000-0000-0012,33.8,Americano with Milk,1
15,2024-03-02 14:38:35,card,ANON-0000-0000-0013,28.9,Americano,1
16,2024-03-02 16:37:24,card,ANON-0000-0000-0014,33.8,Americano with Milk,1
17,2024-03-02 17:34:54,card,ANON-0000-0000-0004,28.9,Americano,1
18,2024-03-03 10:10:43,cash,Cash Payment,40.0,Latte,1
19,2024-03-03 10:27:18,card,ANON-0000-0000-0015,38.7,Latte,1
20,2024-03-03 11:33:56,card,ANON-0000-0000-0016,28.9,Cortado,1
21,2024-03-03 12:26:56,card,ANON-0000-0000-0012,28.9,Americano,1
22,2024-03-03 13:09:36,card,ANON-0000-0000-0017,38.7,Hot Chocolate,1
23,2024-03-03 17:06:40,card,ANON-0000-0000-0018,38.7,Cocoa,1
24,2024-03-03 17:08:45,card,ANON-0000-0000-0019,28.9,Cortado,1
25,2024-03-03 18:03:23,card,ANON-0000-0000-0020,33.8,Americano with Milk,1
26,2024-03-03 18:04:27,card,ANON-0000-0000-0020,33.8,Americano with Milk,1
27,2024-03-03 18:08:04,card,ANON-0000-0000-0020,38.7,Hot Chocolate,1
28,2024-03-04 10:03:51,card,ANON-0000-0000-0001,38.7,Latte,1
29,2024-03-04 10:54:50,card,ANON-0000-0000-0021,38.7,Latte,1